# Site settings
title: Heather and Diego's Wedding
email: drainzos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Simple placeholder until the full wedding site for Heather &amp; Diego's Wedding launches.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://heatherdiegowedding.com" # the base hostname & protocol for your site
github_username: weerd

# Build settings
markdown: kramdown

exclude:
  - README.md
