# Site settings
title: Heather and Diego's Wedding
email: drainzos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://heatherdiegowedding.com" # the base hostname & protocol for your site
github_username: weerd

# Build settings
markdown: kramdown

exclude: [readme.md]
